### ISSUE TITLE
[Option Request] Top of leaves are always solid 

### ISSUE THREAD

**Issue by Estrelaura** [Kurisu-Null/PassableLeaves#1]
An option i always thought would be good to have with passable leaves would be for the top to always be solid, kinda like scaffolding or powdered snow with boots. Maybe a mechanic where if you sprint you start to fall through unless you keep jumping or have leaf walker.

**Comment by Kurisu-Null** [comment]
@Estrelaura that sounds like a nice idea. So you mean only the surface on top of the leaves and the block itself not right, just like with leaf-walker? Only addition is that when you sprint you fall through.
Did i got it correct :) ?

**Comment by Kurisu-Null** [comment]
@Estrelaura updated it and added some new configs. Is it that what you wanted?

**Comment by Kurisu-Null** [comment]
seems like there is a bug on the deployed version. Already on it :(

**Comment by Kurisu-Null** [comment]
@Estrelaura released for 1.19.2 now everything should be working
