### ISSUE TITLE
Waterlogging "fix"

### ISSUE THREAD

**Issue by Estrelaura** [Kurisu-Null/PassableLeaves#14]
I don't know if it's intentional or not, but is there a way to make the water not flow from the leaves when it's waterlogged?

**Comment by SAPH3RE** [comment]
Yeah, dealing with this sucks.

**Comment by Kurisu-Null** [comment]
@SAPH3RE @Estrelaura Fixed the problem. Soon there will be a release :)

**Comment by Xetaxheb** [comment]
Any chance of this fix being backported to 1.19.2? Any of the rest of updates would be nice too but I'd happily take just this fix. Prefer this over passable foliage (no kiwi) but water flowing is a dealbreaker.
