### ISSUE TITLE
1.20.4 Support

### ISSUE THREAD

**Issue by jharlan-hash** [Kurisu-Null/PassableLeaves#15]
Just making an issue to see if there are any plans for supporting 1.20.4.

Thanks!

**Comment by SeanRamey** [comment]
I would also like an update to this mod for a newer minecraft version.

**Comment by Kurisu-Null** [comment]
Alright guys - adding/fixing the issues and updating the version :)

**Comment by SeanRamey** [comment]
> Alright guys - adding/fixing the issues and updating the version :)

Woo hoo! Thanks!

**Comment by Kurisu-Null** [comment]
Release will be on 23 ~ 24

**Comment by SeanRamey** [comment]
> Release will be on 23 ~ 25
> 
> @SeanRamey EDIT: Tomorrow is the day 29. Fixed everything and improved :) Which versions should i support?

Nice thanks a lot!

IMO, you should always try to keep up to date with the latest version. As for older versions, I'm not too sure, but the major versions (eg 1.18.x, 1.19.x, 1.20.x, etc) are likely good candidates, and maybe check what the most popularly modded versions of Minecraft are.

**Comment by Kurisu-Null** [comment]
@SeanRamey version 1.20.4 released. 1.20.5 will take a bit longer now... they adjusted again some stuff... :D
