### ISSUE TITLE
[Bug] Incompat with Distant Horizons 2.1.0 a - Leaves are missing in LOD area

### ISSUE THREAD

**Issue by xR4YM0ND** [Kurisu-Null/PassableLeaves#16]
https://gitlab.com/jeseibel/distant-horizons/-/issues/697

**Comment by TheGoldenKnight** [comment]
There is a similar issue in a similar mod called PassableFoliage.
you can see it here [https://github.com/Snownee/PassableFoliage/issues/43](url), they provided a fix that works for PassableLeaves too

**Comment by Kurisu-Null** [comment]
Will Take a look! 
Thanks for the info :)

**Comment by Kurisu-Null** [comment]
There is a similar issue in a similar mod called PassableFoliage.
you can see it here [https://github.com/Snownee/PassableFoliage/issues/43](https://github.com/Kurisu-Null/PassableLeaves/issues/url), they provided a fix that works for PassableLeaves too

**Comment by Kurisu-Null** [comment]
Will be completely supported in the future without adjusting config of horizons

**Comment by DurekuRyuu** [comment]
Any chance this could be backported to 1.19.2?
