### ISSUE TITLE
Add an option that stops the FOV from changing when entering leaves

### ISSUE THREAD

**Issue by zndrmn** [Kurisu-Null/PassableLeaves#2]
Add an option that stops the FOV from changing when entering leaves. Whenever Im running through jungles my FOV will constantly change, and it's quite annoying.

**Comment by Kurisu-Null** [comment]
I will take a look into that :) Thanks for the input!

**Comment by Kurisu-Null** [comment]
@zndrmn it is an effect created by normal mc logic when the player is slowed down. So you want to have it removed when you are in leaves and slowed down? 

You can also adjust the slow modifier to 0 so no slowing down and no FOV change :)

**Comment by zndrmn** [comment]
yeah I figured. It would be nice if there was a option for it to be disabled
As long as it's not too hard to implement such a feature

**Comment by zndrmn** [comment]
Hmm I don't think 1.19.3 is too important to add support for as most 1.19 mods are now all on 1.19.4. btw great work!

**Comment by Kurisu-Null** [comment]
@zndrmn updated everything and added also other new configurations. :) !
Hope it's not an huge issue that I renamed some configuration fields x_x

**Comment by zndrmn** [comment]
It'll proll be fine :thumbsup:
