### ISSUE TITLE
Please update to 1.20.1 

### ISSUE THREAD

**Issue by BLUEChester** [Kurisu-Null/PassableLeaves#5]
This mod is a must-have, would love to be able to use it on 1.20.1 if you're still working on this

Thanks :)

**Comment by Kurisu-Null** [comment]
Im working on it :) First i will do 1.19.4 and then 1.20 :P

**Comment by Kurisu-Null** [comment]
@BLUEChester 
updated everything and added also other new configurations. :) !
Hope it's not an huge issue that I renamed some configuration fields x_x
